### ISSUE TITLE
404 error using redirect with v3_lazyRouteDiscovery

### ISSUE THREAD

**Issue by srod** [remix-run/remix#10232]
### Reproduction

I'm doing a redirect in a AuthLayout (AuthLayout.tsx) according if session is true/false

And when navigating to /login I have a 404 error

Small reproduction : https://github.com/srod/remix-v3_lazyRouteDiscovery

If you go with your browser to /protected you will have that 404

Error:
No routes matched location "/login"
ErrorResponseImpl {status: 404, statusText: 'Not Found', internal: true, data: 'Error: No route matches URL "/login"',

Discord link if needed: https://discord.com/channels/770287896669978684/1306915010701824063

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.config/nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.config/nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - ~/.config/nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.config/nvm/versions/node/v22.11.0/bin/pnpm
    bun: 1.1.34 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.69
    Edge: 131.0.2903.48
    Safari: 18.1
  npmPackages:
    @remix-run/dev: ^2.14.0 => 2.14.0
    @remix-run/node: ^2.14.0 => 2.14.0
    @remix-run/react: ^2.14.0 => 2.14.0
    @remix-run/serve: ^2.14.0 => 2.14.0
    vite: ^5.1.0 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

Navigate to /login without 404 error.

### Actual Behavior

When navigate to /login we have an error.

**Comment by maximeclaisse** [comment]
This issue also happens in this very simple case :

1. Create a remix app with ` npx create-remix@latest`
2. Create a valid page such as `export default function TestPage() { return <div>Test</div>; }`
3. In _index.tsx, add `useEffect(() => { navigate("/test");  }, []);`
4. Get a 404
5. Refresh the page and get actual page

**Comment by DerJacques** [comment]
We're seeing the same issue when a nav-link is clicked _right_ after the HTML has been rendered. This is hard (but possible) to reproduce manually, but happens consistently in Playwright tests that automate the clicking.

As noted by @maximeclaisse, the issue disappears when strict mode is disabled.

**Comment by fobos531** [comment]
I'm also experiencing this, having a similar use case as @maximeclaisse . Is there something that can be done on RR side to fix this?

**Comment by thomaswelton** [comment]
We're also affected, if a `navigate` is called twice in quick succession and two network requests are made to the manifest endpoint then the navigation will 404.
Might explain why StrictMode caused this error for @maximeclaisse too

**Comment by Print3M** [comment]
Same here. 404 error with `v3_lazyRouteDiscovery: true` with a piece of code like this:
```navigation(`/search/${slug}`)```

It seems like a race-condition-ish sort of thing. Something like: 404 error is faster than lazy route discovery. Just guessing.  

When it doesn't happen:
- Full browser-based load of the buggy page (URL paste, etc.)
- You've been to the buggy page previously and you go there again via `navigate(...)`

When it happens:
- You've never been to the buggy page and you go there via `navigate(...)`

I use flat filename-based routing with `loader(...)` functions:
```
/_index.tsx
/search.$query.tsx
/about.tsx
...
```

**Comment by fobos531** [comment]
for anyone having issues with this, especially with imperative navigation using `navigate`, a workaround that has worked for me in the meantime:

```
const to = "/some/url"

 useEffect(() => {
      document.getElementById('navLink')?.click();
  }, []);

 return <Link className="hidden" to={to} id="navLink" />;
```

**Comment by cloudcreatr** [comment]
No update?? It's still an issue in react router v7. This is a issue please fix it. I have wasted 3 hours onto it

**Comment by derekr** [comment]
I checked out the repo and upgraded to latest remix and didn't get the 404 and navigated to login.

**Comment by brophdawg11** [comment]
I think this was fixed via https://github.com/remix-run/remix/pull/10447.  That would explain why disabling strict mode fixed it - since there were 2 effects calling `navigate` an interrupting the manifest request then.

**Comment by Marcdj-02** [comment]
For me, this is still happening on `v2.15.3`. The workaround, proposed by @fobos531 doesn't work either. What does work is delaying the navigation (by one millisecond or more. `0` does not work):
```ts
  useEffect(() => {
    setTimeout(() => navigate('/dashboard'), 1);
  }, []);
```

**Comment by brophdawg11** [comment]
@Marcdj-02 can you provide a reproduction?

**Comment by lukejagodzinski** [comment]
We've just upgraded our app to Remix 2.16.4 and I can confirm that error still persists. In our case, it also fires fetcher twice so instead of doing work once it does it twice. I'm still investigating this issue. Once I have something I will report and might create reproduction. Fortunately, turning lazy route discovery fixes the problem so we can leave without it for now.

Also building the app and running it doesn't solve the issue either. It's not dev mode specific issue.

**Comment by brophdawg11** [comment]
@lukejagodzinski can you provide a reproduction?

**Comment by lukejagodzinski** [comment]
> [@lukejagodzinski](https://github.com/lukejagodzinski) can you provide a reproduction?

Yes, I will tomorrow

**Comment by lukejagodzinski** [comment]
@brophdawg11 sorry for the delay. I couldn't replicate it from scratch, so I started stripping app from unnecessary stuff to create repro and after removing msw (Mock Service Worker) it started working. At least, it looks like. Before it was ~6 refreshed where in 5 everything loaded properly and in 1 there was a race condition where route loaded dynamically wasn't "discovered" on time. I don't have any weird stuff in msw but maybe it adds some extra delay.

I have one more problem with lazy route discovery where once fetcher call is executed twice instead of once which is weird as the side effect of enabling lazy route discovery. And removing msw didn't help here. So I have to investigate further. But it's probably some issue with our code. However, it's still weird that it only happens after activation of the future flag.

**Comment by lukejagodzinski** [comment]
@brophdawg11 I've tried creating repro but without the success. I've tried from scratch but adding msw alone doesn't break Remix app yet. Then I tried removing code from our app but it's to hard as everything is connected and I've ended up with the version almost like the one created from scratch and there is no bug. I'm not sure, why msw.js is causing this issue only in certain situations. Maybe it's the amount of routes or maybe it's how much time each route's loader takes to load. I've tried multiple things but without the success.

The thing that loads the non-discovered yet route looks like this:

```tsx
export default function BuildProjectPage() {
  const loaderPath = "/build/abc/comments";

  useLoaderData();

  const [comments, setComments] = useState(null);
  const fetcher = useFetcher();

  useEffect(() => {
    fetcher.load(loaderPath); // Initial fetch
    const intervalId = setInterval(() => fetcher.load(loaderPath), 10_000);
    return () => clearInterval(intervalId);
  }, []);

  useEffect(() => {
    setComments(fetcher.data);
  }, [fetcher.data]);

  return (
    <div>
      <p>BUILD</p>
      <div>
        Comments: <pre>{JSON.stringify(comments, null, 2)}</pre>
      </div>
      <Outlet />
    </div>
  );
}
```

It's not the leaf in the routes tree but one level higher. It loads `/comments` on initial load but also on interval every 10 seconds. I might refresh multiple times and it will work normally. But once in a while it will not discover the `/comments` route. Also there is no link to `/comments` route everywhere on the site before entering this page, so it can't discover it.

How does the mechanism discovery work in practice? Does it only rely on links?

**Comment by brophdawg11** [comment]
Normal discovery happens on navigations or fetcher calls.  If you use a `<Link>` that enabled "eager discovery" and does it before the link is clicked.  Interruptions _should_ be handled but maybe it's the interval.  If you lower that to a few in rapid succession does it cause the issue?

**Comment by lukejagodzinski** [comment]
@brophdawg11 I think, I found the source of the problem. It wasn't loading route on interval on in the useEffect. It was one of the child components doing revalidation:

```tsx
const { revalidate } = useRevalidator();

useEffect(() => {
  if (/* ... */) {
    revalidate();
  }
}, [/* ... */]);
```

When I removed revalidation, the problem went away. I will try to create reproduction this week.

**Comment by lukejagodzinski** [comment]
@brophdawg11 ok I've prepare reproduction here: https://github.com/lukejagodzinski/remix-lazy-discovery-repro and described steps to reproduce an issue.

**Comment by brophdawg11** [comment]
The fact that removing MSW fixes it is a bit curious.  Are you able to reproduce without MSW in the mix?

**Comment by brophdawg11** [comment]
Could you open a new issue in the React Router repo and we can look into fixing it there?  If this is blocking you from upgrading you can disable lazy route discovery with the [config flag](https://reactrouter.com/start/changelog#routediscovery-config-option) we recently introduced

**Comment by lukejagodzinski** [comment]
I know this issue is closed but just writing for the posterity. I went back to this problem and finally I resolved this issue. I guess, I needed some break from the problem as going back to it it appeared to be trivial. Basically, you can't call `revalidate` from `useRevalidate` hook on component mount. Remix is still discovering routes at this point and if you revalidate you might just call routes that weren't yet discovered. That's it. I'm not sure if it's a bug. Would be nice if `revalidate` waited with revalidation but I guess there is no easy way to "wait". So it was more of the issue on my side, I guess.
