### ISSUE TITLE
Source map URL replace does not work on cloudflare-pages build target.

### ISSUE THREAD

**Issue by fabiankaestner** [remix-run/remix#3768]
### What version of Remix are you using?

1.6.4

### Steps to Reproduce

Setup a cloudflare-workers remix app.
Start the application in development.
Provoke a stacktrace.

### Expected Behavior

I have sourcemaps available.

### Actual Behavior

I do not have sourcemaps, instead I get the stacktraces from the generated [[path]].js file.

**Comment by fabiankaestner** [comment]
This happens because the server component generated for a cloudflare-pages deployment are named [[path]].js. The regex that is used for rewriting the source map URL doesn't account for unescaped [] in the filename, and thus fails to replace the URL correctly as implemented in PR #2065.
The problem is here:
https://github.com/remix-run/remix/blob/f752f8256ed5fba35b7878f7e14ef137968a115c/packages/remix-dev/compiler.ts#L514-L518
we should be escaping the [], for example like this
```ts
let escapedFilename = filename
    .replace(/\./g, "\\.")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
let pattern = `(//# sourceMappingURL=)(.*)${escapedFilename}`;
let contents = Buffer.from(file.contents).toString("utf-8");
contents = contents.replace(new RegExp(pattern), `$1${filename}`);
await fse.writeFile(file.path, contents);
```

I'd be happy to do a PR with the change, however I'm unable to write a unit test for it. To be able to write a unit test for this, I'd have to be able to provoke the build artifacts naming to be like a cloudflare-pages build target.
Maybe someone that knows how the remix test work could help me out there?

**Comment by kiliman** [comment]
Ah, thanks. At the time I wrote that, I hadn't seen any other patterns.

**Comment by kiliman** [comment]
If your change works for both cloudflare and other adapters, I'd go ahead and submit the PR.

**Comment by fabiankaestner** [comment]
Well, I don't see any reason it wouldn't work 🤔

**Comment by kiliman** [comment]
You can also simplify the replace as
```ts
let escapedFilename = filename.replace(/([.\[\]])/g, '\\$1')
```
`[[abc.123]]` => `\\[\\[abc\\.123\\]\\]`

**Comment by fabiankaestner** [comment]
Ooh, that's interesting, the . loses its unescaped meaning inside a character set?

**Comment by brophdawg11** [comment]
This is resolved by #7574 and will; be available in the next release

**Comment by xdivby0** [comment]
I am not that sure it will be solved. I applied the exact changes via patch-package and while it does now generate source maps, _they are not used by cloudflare_. The errors that get logged / sent to my webhook still have the unreadable stacktrace in it. 

Can anyone confirm or reject my observations?

**Comment by BrandonNoad** [comment]
@xdivby0 That is a different issue. There is a thread in the Discord server discussing that.
