### ISSUE TITLE
"Error: Remix Vite plugin can't detect preamble. Something is wrong." when running component tests with Vitest

### ISSUE THREAD

**Issue by amanape** [remix-run/remix#8982]
### Reproduction

Go to https://stackblitz.com/edit/remix-run-remix-b7fgeb?file=__tests__%2Fexample.spec.tsx and run `npx vitest` to see the error.

Regular unit tests run fine, problem appeared when integrating component testing with `@testing-library/react` (which in turn required me to install `happy-dom` or `jsdom` for the testing environment).

Defining the components _inside_ the test do not cause an error.

I was able to trace the issue to the `vite.config.ts` file, where including any configurations related to `vitest` will cause it to fail. Moving the `vitest` configurations to `vitest.config.ts` and [merging the two configuration files as advised by the official documentation](https://vitest.dev/guide/#configuring-vitest) also causes the same error.

## Temporary Solution
The only (temporary) solution I found was to separate `vitest.config.ts` and `vite.config.ts`, then everything works as expected. But that is not a good solution as according to the official documentation, **overrides the vite file**.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 116.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/.yarn/bin/yarn
    npm: 10.3.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.109
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.8.0 => 2.8.0 
    @remix-run/node: ^2.8.0 => 2.8.0 
    @remix-run/react: ^2.8.0 => 2.8.0 
    @remix-run/serve: ^2.8.0 => 2.8.0 
    @remix-run/testing: ^2.8.0 => 2.8.0 
    vite: ^5.1.0 => 5.1.5
```

### Used Package Manager

npm

### Expected Behavior

Tests should work as expecting without throwing

### Actual Behavior

Test fail because of reasons unrelated to tests

**Comment by martialanouman** [comment]
It ran into the same error too while trying to run react component tests

**Comment by CharlesErrington** [comment]
I am also having this exact error.

**Comment by martialanouman** [comment]
Any update on this ?

**Comment by amanape** [comment]
@martialanouman 
> The only (temporary) solution I found was to separate vitest.config.ts and vite.config.ts, then everything works as expected. But that is not a good solution as according to the official documentation, overrides the vite file.

**Comment by martialanouman** [comment]
Thanks @amanape 

I saw that and use it for now, but that doesn't feel clean

**Comment by pcattori** [comment]
Currently we recommend that [the `remix` plugin is omitted when running with Vitest](https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook).
There's a bit of work to do on our end to figure out how best to integrate with tools like Vitest and Storybook so that this sort of workaround isn't required.

**Comment by yegorkay** [comment]
If I did the conditional logic of `process.env.VITEST && remix()` I would get a new error in some of my tests:

```
ReferenceError: React is not defined
```

If you were on a Vite React SPA previously, I'm finding that you would need to keep your `@vitejs/plugin-react` around just for vitest:

```js
import reactVitest from '@vitejs/plugin-react'
import { vitePlugin as remix } from '@remix-run/dev';
import { defineConfig, loadEnv } from "vite";

export default defineConfig({
  plugins: [process.env.VITEST ? reactVitest() : remix()],
  // rest of the config
});
```

**Comment by acelaya** [comment]
> Currently we recommend that [the `remix` plugin is omitted when running with Vitest](https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook).
> There's a bit of work to do on our end to figure out how best to integrate with tools like Vitest and Storybook so that this sort of workaround isn't required.

This generally works well, but I'm facing some issues when trying to test remix routes using [`@remix-run/testing`](https://remix.run/docs/en/main/other-api/testing). Basically, no matter what I pass, when rendering the `RemixStub`, it always results in a 404 error page.

Could that be related with the fact that the remix vite plugin is not loaded while running tests with vite?

**Comment by R0BB3RT** [comment]
> > Currently we recommend that [the `remix` plugin is omitted when running with Vitest](https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook).
> > There's a bit of work to do on our end to figure out how best to integrate with tools like Vitest and Storybook so that this sort of workaround isn't required.
> 
> This generally works well, but I'm facing some issues when trying to test remix routes using [`@remix-run/testing`](https://remix.run/docs/en/main/other-api/testing). Basically, no matter what I pass, when rendering the `RemixStub`, it always results in a 404 error page.
> 
> Could that be a side effect of not loading the remix vite plugin while running tests with vite?

Currently facing the same issue. The "Remix Vite plugin can't detect preamble. Something is wrong." was solved. However now my tests using `createRemixStub` always render 404 error page which makes them fail.

Any solution?

**Comment by brianbancroft** [comment]
I am running into this exact error with a fresh remix app which attempts to use vitest with jsdom. I have another project which uses React Router which I want to port over to remix. While the app works, the tests cannot due to this issue and I am blocked. 

## Reproduction

https://github.com/brianbancroft/remix-cant-use-vitest

**Comment by christophersesugh** [comment]
This will fix the issue
```
import { vitePlugin as remix } from "@remix-run/dev";
import { installGlobals } from "@remix-run/node";
import tsconfigPaths from "vite-tsconfig-paths";
import { defineConfig } from "vite";

installGlobals();

const MODE = process.env.NODE_ENV;

export default defineConfig({
  build: {
    cssMinify: MODE === "production",
    rollupOptions: {
      external: [/node:.*/, "stream", "crypto", "fsevents"],
    },
  },
  server: {
    watch: {
      ignored: ["**/playwright-report/**"],
    },
  },
  plugins: [
    process.env.NODE_ENV === "test"
      ? null
      : remix({
          ignoredRouteFiles: ["**/*.css"],
        }),
    tsconfigPaths(),
  ],
  test: {
    include: ["**/__tests__/**.{js,jsx,ts,tsx}"],
    environment: "jsdom",
    setupFiles: ["./tests/setup/setup-tests-env.ts"],
    restoreMocks: true,
    coverage: {
      exclude: ["**/__tests__/**"],
      include: ["app/**/*.{ts,tsx}"],
      all: true,
    },
    alias: {
      "~": "/app",
    },
  },
});
```

This is a typical config file

```
 plugins: [
    process.env.NODE_ENV === "test"
      ? null
      : remix({
          ignoredRouteFiles: ["**/*.css"],
        }),
    tsconfigPaths(),
  ],
```

Checkout this issue [https://github.com/remix-run/remix/issues/9871](https://github.com/remix-run/remix/issues/9871)

**Comment by msatgh** [comment]
> > > Currently we recommend that [the `remix` plugin is omitted when running with Vitest](https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook).
> > > There's a bit of work to do on our end to figure out how best to integrate with tools like Vitest and Storybook so that this sort of workaround isn't required.
> > 
> > 
> > This generally works well, but I'm facing some issues when trying to test remix routes using [`@remix-run/testing`](https://remix.run/docs/en/main/other-api/testing). Basically, no matter what I pass, when rendering the `RemixStub`, it always results in a 404 error page.
> > Could that be a side effect of not loading the remix vite plugin while running tests with vite?
> 
> For anyone else who ends up here. The issue I described there is now solved with react-router 7 and `createRoutesStub` instead of `createRemixStub`, but make sure you use it as described in https://reactrouter.com/start/framework/testing, paying extra attention to the `path` you pass, as it needs to match the last entry in the `initialEntries` array.

I still have problems with it. The loader function in createRoutesStub isn't called. I guess this is because the vite plugin for reactRouter has to be disabled if the vitest plugin is active. Otherwise the error initially discussed here will reappear. Thus i cannot get data from the mocked loader function into the component. Maybe i missed the solution to this...

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
